### ISSUE TITLE
[FEAT] Use Hubber in Banner Image

### ISSUE THREAD

**Issue by naomi-lgbt** [rohan-kulkarni-25/rohan-kulkarni-25#3]
Coming from [Eddie's Live Stream](https://www.youtube.com/watch?v=biy__J7abMU) for reference.

Great work on using "Collaboration first, code second" on the banner. We would recommend replacing the smiley art (in the laptop) with the [Hubber mascot from EddieHub](https://github.com/eddieHubCommunity/branding).

![image](https://user-images.githubusercontent.com/63889819/117705713-3d2a1e00-b181-11eb-9ed4-28a17a1c40ca.png)

**Comment by rohan-kulkarni-25** [comment]
Thanks !
